FROM rnakato/ubuntu:2022.08
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

ENV PATH /miniconda3/bin:$PATH
WORKDIR /opt
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    automake \
    build-essential \
    bzip2 \
    default-jdk \
    emacs \
    fastqc \
    ffmpeg \
    gawk \
    gcc \
    git \
    gpg-agent \
    imagemagick \
    less \
    libcurl4-openssl-dev \
    libfontconfig1-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    liblz4-tool \
    libncurses-dev \
    libncurses5 \
    libssl-dev \
    libxkbcommon-x11-0 \
    libxml2-dev \
    make \
    msttcorefonts \
    pigz \
    time \
    unzip \
    vim \
    wget \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# BWA version 0.7.17 or higher
COPY bwa-0.7.17.tar.bz2 bwa-0.7.17.tar.bz2
RUN tar xvfj bwa-0.7.17.tar.bz2 \
    && cd bwa-0.7.17 \
    && make \
    && cd .. \
    && rm bwa-0.7.17.tar.bz2

# Chromap 0.2.1
COPY chromap-0.2.1_x64-linux.tar.bz2 chromap-0.2.1_x64-linux.tar.bz2
RUN tar xvfj chromap-0.2.1_x64-linux.tar.bz2 \
     && rm chromap-0.2.1_x64-linux.tar.bz2

# pairsqc
RUN wget --progress=dot:giga https://github.com/4dn-dcic/pairsqc/archive/0.2.3.tar.gz \
    && tar -xzf 0.2.3.tar.gz \
    && rm 0.2.3.tar.gz

# R 4.x
RUN echo "deb https://cran.rstudio.com/bin/linux/ubuntu focal-cran40/" | tee -a /etc/apt/sources.list \
    && curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9" | apt-key add \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    r-base r-base-core r-recommended r-base-dev libclang-dev libxkbcommon-x11-0 \
    && apt-get upgrade -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# R packages
RUN R -e "install.packages(c('BiocManager'))" \
    && R -e "BiocManager::install(version = '3.16', ask = FALSE)" \
    && R CMD javareconf \
    && R -e "install.packages(c('devtools', 'Nozzle.R1', 'sm', 'stringr', 'BiocManager'))" \
    && R -e "BiocManager::install(c('ShortRead','GenomeInfoDb','GenomicAlignments','BiocGenerics','Biostrings','GenomicRanges','IRanges', 'S4Vectors', 'matrixStats'))" \
    && R -e 'library(devtools); install_url("https://github.com/SooLee/plotosaurus/archive/0.9.2.zip")'

RUN ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 /usr/lib/x86_64-linux-gnu/libffi.so.6

### Python
RUN wget --progress=dot:giga https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh \
    && bash Miniconda3-py37_4.12.0-Linux-x86_64.sh -p /miniconda3 -b \
    && rm Miniconda3-py37_4.12.0-Linux-x86_64.sh

RUN conda install -y matplotlib numpy scipy pandas ipython jupyter jupyterlab seaborn cython \
    && conda install -c conda-forge -c bioconda pairtools=0.3.0 fithic \
    && conda install -y -c bioconda hic2cool samtools cooltools cooler

RUN conda create -y -n hicexplorer python=3.7 jupyter notebook ipykernel \
    && source activate hicexplorer \
#    && conda install hicexplorer -c bioconda -c conda-forge \
    && pip install --no-cache-dir hicexplorer \
    && python -m ipykernel install --name=hicexplorer \
    && jupyter kernelspec list \
    && conda deactivate

#    && pip install --no-cache-dir cooltools

# HOMER
RUN mkdir HOMER && cd HOMER \
    && mkdir bin cpp update \
    && wget http://homer.ucsd.edu/homer/configureHomer.pl \
    && perl configureHomer.pl -install human-o \
    && perl configureHomer.pl -install human-p \
    && perl configureHomer.pl -install mouse-o \
    && perl configureHomer.pl -install mouse-p \
    && perl configureHomer.pl -install zebrafish-o \
    && perl configureHomer.pl -install yeast-o

# Mango
RUN R -e "install.packages(c('hash','Rcpp','optparse','readr'))" \
    && git clone https://github.com/dphansti/mango.git \
    && R CMD INSTALL --no-multiarch --with-keep.source mango
# Mango (wang)
#RUN git clone https://github.com/wangjk321/mango_multithreads_wang.git \
#    && mv mango_multithreads_wang mango \
#    && R CMD INSTALL --no-multiarch --with-keep.source mango

RUN pip install --no-cache-dir h1d hic-straw phic tabulate
# pastis
# iced installation tips: https://github.com/scikit-learn/scikit-learn/discussions/21931
# about "No module named 'numpy.distutils._msvccompiler' in numpy.distutil"
RUN pip install iced --no-build-isolation --no-cache-dir \
    && pip install pastis --no-cache-dir \
# JuiceBox
    && pip install --no-cache-dir git+https://github.com/igvteam/juicebox-notebook.git
# CustardPy
#RUN pip install -U --no-cache-dir -i https://test.pypi.org/simple/ custardpy==0.2.11
RUN pip install --no-cache-dir custardpy==0.0.21

# FitHiC
# ChIAPoP
COPY ChIAPoP_0.99.9.7.tar.gz ChIAPoP_0.99.9.7.tar.gz
RUN R CMD INSTALL ChIAPoP_0.99.9.7.tar.gz \
    && rm ChIAPoP_0.99.9.7.tar.gz

# installing gawk for juicer
RUN echo 'alias awk=gawk' >> ~/.bashrc

# wrapper
COPY Cooler-restriction_sites /Cooler-restriction_sites
RUN gunzip /Cooler-restriction_sites/*gz
COPY scripts/ scripts
RUN chmod +x /opt/scripts/* /opt/scripts/pastis/*

RUN ln -s /opt/pairsqc-*/ /opt/scripts/pairsqc \
    && ln -s /miniconda3/pkgs/pairix-*/bin/ scripts/pairix

COPY juicer_tools_1.22.01.jar /opt/juicer_tools.jar

# set path
ENV PATH=$PATH:/opt:/opt/bwa-0.7.17:/opt/pairix-0.3.7:/opt/pairsqc-0.2.3:/opt/scripts:/opt/scripts/pastis:/opt/scripts/pairix:/opt/scripts/pairsqc:/opt/HOMER/bin/:/miniconda3/envs/hicexplorer/bin/

# supporting UTF-8
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

USER ubuntu
CMD ["/bin/bash"]
