FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
LABEL original from aidenlab/juicer, modified by Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>

# For sorting, LC_ALL is C
ENV LC_ALL C
ENV PATH=/opt/conda/bin/:$PATH:/opt:/opt/bwa-0.7.17:/opt/juicer/scripts:/opt/juicer/scripts/common:/opt/scripts
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/
USER root

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
     bzip2 \
     curl \
     default-jdk \
     fastqc \
     gawk \
     gcc \
     git \
     libbz2-dev \
     libcurl4-gnutls-dev \
     libz-dev \
     locales \
     make \
     pigz \
     qtcreator \
     samtools \
     wget \
     unzip \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

# BWA version 0.7.17 or higher
COPY bwa-0.7.17.tar.bz2 bwa-0.7.17.tar.bz2
RUN tar xvfj bwa-0.7.17.tar.bz2 \
    && cd bwa-0.7.17 \
    && make \
    && cd .. \
    && rm bwa-0.7.17.tar.bz2

# Anaconda3 (2020.02)
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh -O ~/anaconda.sh \
     && bash ~/anaconda.sh -b -p /opt/conda \
     && rm ~/anaconda.sh \
     && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

RUN pip install --no-cache-dir hic-straw phic h1d \
    pip install --no-cache-dir git+https://github.com/igvteam/juicebox-notebook.git

# R
RUN echo "deb https://cran.rstudio.com/bin/linux/ubuntu focal-cran40/" | tee -a /etc/apt/sources.list \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 51716619E084DAB9\
    && apt-get update \
    && apt-get install -y --no-install-recommends r-base r-base-core r-recommended r-base-dev libclang-dev libxkbcommon-x11-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c('ggplot2','reshape2','devtools'), repos='https://cran.ism.ac.jp/')"

# GAWK has the 'and' function, needed for chimeric_blacklist
RUN echo 'alias awk=gawk' >> ~/.bashrc

# Need to be sure we have this for stats
RUN locale-gen en_US.UTF-8

# Install Juicer
COPY juicer-1.6 /opt/juicer
RUN unpigz /opt/juicer/restriction_sites/*txt.gz

# Install Juicer tools
COPY juicer_tools.1.22.01.jar /opt/juicer/scripts/common/juicer_tools.jar

# JuiceBox
COPY Juicebox.jar /opt/Juicebox.jar
#RUN pip install --no-cache-dir git+https://github.com/igvteam/juicebox-notebook.git

COPY motiffiles motiffiles
RUN unpigz /opt/motiffiles/*gz
COPY juicer_tools.1.9.9_jcuda.0.8.jar /opt/juicer_tools.1.9.9_jcuda.0.8.jar

COPY scripts /opt/scripts
COPY bedtools /usr/local/bin/bedtools
RUN chmod +x scripts/* /usr/local/bin/bedtools /opt/juicer/scripts/common/* /opt/juicer/scripts/*

# Error "Qt: Failed to create XKB context!"
# https://stackoverflow.com/questions/26974644/no-keyboard-input-in-qt-creator-after-update-to-qt5
ENV QT_XKB_CONFIG_ROOT /usr/share/X11/xkb
#RUN qtcreator
